// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.proto

/*
Package bean is a generated protocol buffer package.

It is generated from these files:
	im.proto

It has these top-level messages:
	SingleMsg
	GroupMsg
	MsgSendRes
	MsgReq
	MsgReqRes
	LoginReq
	MsgReqAck
	MsgInform
	TcpProtocol
	UdpProtocol
*/
package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtocolTypeEnum int32

const (
	// proto3必须要有这个0
	ProtocolTypeEnum_UNKNOWN ProtocolTypeEnum = 0
	// 登录包
	ProtocolTypeEnum_LOGIN ProtocolTypeEnum = 1
	// 心跳包
	ProtocolTypeEnum_PONG ProtocolTypeEnum = 2
	// 消息请求包
	ProtocolTypeEnum_MSG_REQ ProtocolTypeEnum = 3
	// 新消息通知包
	ProtocolTypeEnum_MSG_INFORM ProtocolTypeEnum = 4
	// 消息请求响应包
	ProtocolTypeEnum_MSG_REQ_RES ProtocolTypeEnum = 5
	// 请求ack包
	ProtocolTypeEnum_MSG_REQ_ACK ProtocolTypeEnum = 6
	// 单消息发送包
	ProtocolTypeEnum_MSG_SEND_SINGLE ProtocolTypeEnum = 7
	// 群消息发送包
	ProtocolTypeEnum_MSG_SEND_GROUP ProtocolTypeEnum = 8
	// 消息发送响应包
	ProtocolTypeEnum_MSG_SEND_RES ProtocolTypeEnum = 9
)

var ProtocolTypeEnum_name = map[int32]string{
	0: "UNKNOWN",
	1: "LOGIN",
	2: "PONG",
	3: "MSG_REQ",
	4: "MSG_INFORM",
	5: "MSG_REQ_RES",
	6: "MSG_REQ_ACK",
	7: "MSG_SEND_SINGLE",
	8: "MSG_SEND_GROUP",
	9: "MSG_SEND_RES",
}
var ProtocolTypeEnum_value = map[string]int32{
	"UNKNOWN":         0,
	"LOGIN":           1,
	"PONG":            2,
	"MSG_REQ":         3,
	"MSG_INFORM":      4,
	"MSG_REQ_RES":     5,
	"MSG_REQ_ACK":     6,
	"MSG_SEND_SINGLE": 7,
	"MSG_SEND_GROUP":  8,
	"MSG_SEND_RES":    9,
}

func (x ProtocolTypeEnum) String() string {
	return proto.EnumName(ProtocolTypeEnum_name, int32(x))
}
func (ProtocolTypeEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgTypeEnum int32

const (
	MsgTypeEnum_DEFAULT MsgTypeEnum = 0
	// 文本
	MsgTypeEnum_TEXT    MsgTypeEnum = 1
	MsgTypeEnum_EMOJI   MsgTypeEnum = 2
	MsgTypeEnum_PUSHCMD MsgTypeEnum = 3
	MsgTypeEnum_IMG     MsgTypeEnum = 4
	// 消息分片
	MsgTypeEnum_VOICE MsgTypeEnum = 5
	// 消息描述
	MsgTypeEnum_VOICE_DES MsgTypeEnum = 6
)

var MsgTypeEnum_name = map[int32]string{
	0: "DEFAULT",
	1: "TEXT",
	2: "EMOJI",
	3: "PUSHCMD",
	4: "IMG",
	5: "VOICE",
	6: "VOICE_DES",
}
var MsgTypeEnum_value = map[string]int32{
	"DEFAULT":   0,
	"TEXT":      1,
	"EMOJI":     2,
	"PUSHCMD":   3,
	"IMG":       4,
	"VOICE":     5,
	"VOICE_DES": 6,
}

func (x MsgTypeEnum) String() string {
	return proto.EnumName(MsgTypeEnum_name, int32(x))
}
func (MsgTypeEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// *
// 单聊消息
type SingleMsg struct {
	FromUserId int64  `protobuf:"varint,1,opt,name=fromUserId" json:"fromUserId,omitempty"`
	ToUserId   int64  `protobuf:"varint,2,opt,name=toUserId" json:"toUserId,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	ClientTime string `protobuf:"bytes,4,opt,name=clientTime" json:"clientTime,omitempty"`
	ServerTime string `protobuf:"bytes,5,opt,name=serverTime" json:"serverTime,omitempty"`
	MsgType    string `protobuf:"bytes,6,opt,name=msgType" json:"msgType,omitempty"`
	SyncKey    int64  `protobuf:"varint,7,opt,name=syncKey" json:"syncKey,omitempty"`
	MsgId      string `protobuf:"bytes,8,opt,name=msgId" json:"msgId,omitempty"`
	DeviceType int32  `protobuf:"varint,9,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *SingleMsg) Reset()                    { *m = SingleMsg{} }
func (m *SingleMsg) String() string            { return proto.CompactTextString(m) }
func (*SingleMsg) ProtoMessage()               {}
func (*SingleMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SingleMsg) GetFromUserId() int64 {
	if m != nil {
		return m.FromUserId
	}
	return 0
}

func (m *SingleMsg) GetToUserId() int64 {
	if m != nil {
		return m.ToUserId
	}
	return 0
}

func (m *SingleMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SingleMsg) GetClientTime() string {
	if m != nil {
		return m.ClientTime
	}
	return ""
}

func (m *SingleMsg) GetServerTime() string {
	if m != nil {
		return m.ServerTime
	}
	return ""
}

func (m *SingleMsg) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *SingleMsg) GetSyncKey() int64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

func (m *SingleMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *SingleMsg) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

// *
// 群聊消息
type GroupMsg struct {
	FromUserId int64  `protobuf:"varint,1,opt,name=fromUserId" json:"fromUserId,omitempty"`
	ToGroupId  int64  `protobuf:"varint,2,opt,name=toGroupId" json:"toGroupId,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	ClientTime string `protobuf:"bytes,4,opt,name=clientTime" json:"clientTime,omitempty"`
	ServerTime string `protobuf:"bytes,5,opt,name=serverTime" json:"serverTime,omitempty"`
	MsgType    string `protobuf:"bytes,6,opt,name=msgType" json:"msgType,omitempty"`
	SyncKey    int64  `protobuf:"varint,7,opt,name=syncKey" json:"syncKey,omitempty"`
	MsgId      string `protobuf:"bytes,8,opt,name=msgId" json:"msgId,omitempty"`
	DeviceType int32  `protobuf:"varint,9,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *GroupMsg) Reset()                    { *m = GroupMsg{} }
func (m *GroupMsg) String() string            { return proto.CompactTextString(m) }
func (*GroupMsg) ProtoMessage()               {}
func (*GroupMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GroupMsg) GetFromUserId() int64 {
	if m != nil {
		return m.FromUserId
	}
	return 0
}

func (m *GroupMsg) GetToGroupId() int64 {
	if m != nil {
		return m.ToGroupId
	}
	return 0
}

func (m *GroupMsg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *GroupMsg) GetClientTime() string {
	if m != nil {
		return m.ClientTime
	}
	return ""
}

func (m *GroupMsg) GetServerTime() string {
	if m != nil {
		return m.ServerTime
	}
	return ""
}

func (m *GroupMsg) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *GroupMsg) GetSyncKey() int64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

func (m *GroupMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupMsg) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

// *
// 消息发送响应
type MsgSendRes struct {
	MsgId string `protobuf:"bytes,1,opt,name=msgId" json:"msgId,omitempty"`
	Flag  bool   `protobuf:"varint,2,opt,name=flag" json:"flag,omitempty"`
}

func (m *MsgSendRes) Reset()                    { *m = MsgSendRes{} }
func (m *MsgSendRes) String() string            { return proto.CompactTextString(m) }
func (*MsgSendRes) ProtoMessage()               {}
func (*MsgSendRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MsgSendRes) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *MsgSendRes) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

// *
// 消息请求
type MsgReq struct {
	UserId      int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	SyncKey     int64 `protobuf:"varint,2,opt,name=syncKey" json:"syncKey,omitempty"`
	PageSize    int32 `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	CurrentPage int32 `protobuf:"varint,4,opt,name=currentPage" json:"currentPage,omitempty"`
}

func (m *MsgReq) Reset()                    { *m = MsgReq{} }
func (m *MsgReq) String() string            { return proto.CompactTextString(m) }
func (*MsgReq) ProtoMessage()               {}
func (*MsgReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MsgReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgReq) GetSyncKey() int64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

func (m *MsgReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *MsgReq) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

// *
// 消息请求响应
type MsgReqRes struct {
	SyncKey int64        `protobuf:"varint,1,opt,name=syncKey" json:"syncKey,omitempty"`
	Msgs    []*SingleMsg `protobuf:"bytes,2,rep,name=msgs" json:"msgs,omitempty"`
}

func (m *MsgReqRes) Reset()                    { *m = MsgReqRes{} }
func (m *MsgReqRes) String() string            { return proto.CompactTextString(m) }
func (*MsgReqRes) ProtoMessage()               {}
func (*MsgReqRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MsgReqRes) GetSyncKey() int64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

func (m *MsgReqRes) GetMsgs() []*SingleMsg {
	if m != nil {
		return m.Msgs
	}
	return nil
}

// *
// 登录请求
type LoginReq struct {
	UerId      int64 `protobuf:"varint,1,opt,name=uerId" json:"uerId,omitempty"`
	DeviceType int32 `protobuf:"varint,2,opt,name=deviceType" json:"deviceType,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginReq) GetUerId() int64 {
	if m != nil {
		return m.UerId
	}
	return 0
}

func (m *LoginReq) GetDeviceType() int32 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

// *
// 消息请求响应ack
type MsgReqAck struct {
	UserId  int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	SyncKey int64 `protobuf:"varint,2,opt,name=syncKey" json:"syncKey,omitempty"`
}

func (m *MsgReqAck) Reset()                    { *m = MsgReqAck{} }
func (m *MsgReqAck) String() string            { return proto.CompactTextString(m) }
func (*MsgReqAck) ProtoMessage()               {}
func (*MsgReqAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MsgReqAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgReqAck) GetSyncKey() int64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

// *
// 新消息通知
type MsgInform struct {
	UserId  int64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	SyncKey int64 `protobuf:"varint,2,opt,name=syncKey" json:"syncKey,omitempty"`
}

func (m *MsgInform) Reset()                    { *m = MsgInform{} }
func (m *MsgInform) String() string            { return proto.CompactTextString(m) }
func (*MsgInform) ProtoMessage()               {}
func (*MsgInform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MsgInform) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MsgInform) GetSyncKey() int64 {
	if m != nil {
		return m.SyncKey
	}
	return 0
}

// 协议
type TcpProtocol struct {
	// 协议Id ProtocolTypeEnum里的值
	ProtocolType int32 `protobuf:"varint,1,opt,name=protocolType" json:"protocolType,omitempty"`
	// 协议内容，也就是消息内容
	ProtocolContent []byte `protobuf:"bytes,2,opt,name=protocolContent,proto3" json:"protocolContent,omitempty"`
}

func (m *TcpProtocol) Reset()                    { *m = TcpProtocol{} }
func (m *TcpProtocol) String() string            { return proto.CompactTextString(m) }
func (*TcpProtocol) ProtoMessage()               {}
func (*TcpProtocol) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TcpProtocol) GetProtocolType() int32 {
	if m != nil {
		return m.ProtocolType
	}
	return 0
}

func (m *TcpProtocol) GetProtocolContent() []byte {
	if m != nil {
		return m.ProtocolContent
	}
	return nil
}

// 协议
type UdpProtocol struct {
	// 协议Id
	ProtocolType    int32  `protobuf:"varint,1,opt,name=protocolType" json:"protocolType,omitempty"`
	ProtocolContent []byte `protobuf:"bytes,2,opt,name=protocolContent,proto3" json:"protocolContent,omitempty"`
	ToUuserId       int64  `protobuf:"varint,3,opt,name=toUuserId" json:"toUuserId,omitempty"`
	Fromaddress     string `protobuf:"bytes,4,opt,name=fromaddress" json:"fromaddress,omitempty"`
}

func (m *UdpProtocol) Reset()                    { *m = UdpProtocol{} }
func (m *UdpProtocol) String() string            { return proto.CompactTextString(m) }
func (*UdpProtocol) ProtoMessage()               {}
func (*UdpProtocol) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UdpProtocol) GetProtocolType() int32 {
	if m != nil {
		return m.ProtocolType
	}
	return 0
}

func (m *UdpProtocol) GetProtocolContent() []byte {
	if m != nil {
		return m.ProtocolContent
	}
	return nil
}

func (m *UdpProtocol) GetToUuserId() int64 {
	if m != nil {
		return m.ToUuserId
	}
	return 0
}

func (m *UdpProtocol) GetFromaddress() string {
	if m != nil {
		return m.Fromaddress
	}
	return ""
}

func init() {
	proto.RegisterType((*SingleMsg)(nil), "bean.SingleMsg")
	proto.RegisterType((*GroupMsg)(nil), "bean.GroupMsg")
	proto.RegisterType((*MsgSendRes)(nil), "bean.MsgSendRes")
	proto.RegisterType((*MsgReq)(nil), "bean.MsgReq")
	proto.RegisterType((*MsgReqRes)(nil), "bean.MsgReqRes")
	proto.RegisterType((*LoginReq)(nil), "bean.LoginReq")
	proto.RegisterType((*MsgReqAck)(nil), "bean.MsgReqAck")
	proto.RegisterType((*MsgInform)(nil), "bean.MsgInform")
	proto.RegisterType((*TcpProtocol)(nil), "bean.TcpProtocol")
	proto.RegisterType((*UdpProtocol)(nil), "bean.UdpProtocol")
	proto.RegisterEnum("bean.ProtocolTypeEnum", ProtocolTypeEnum_name, ProtocolTypeEnum_value)
	proto.RegisterEnum("bean.MsgTypeEnum", MsgTypeEnum_name, MsgTypeEnum_value)
}

func init() { proto.RegisterFile("im.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x18, 0xac, 0xff, 0x12, 0xfb, 0x73, 0x69, 0x56, 0x4b, 0x85, 0xac, 0x0a, 0xa1, 0xc8, 0x5c, 0xa2,
	0x1e, 0x7a, 0x00, 0x89, 0x1b, 0x12, 0x55, 0xe2, 0x1a, 0xb7, 0xb1, 0x1d, 0xd6, 0x31, 0x20, 0x71,
	0x88, 0x52, 0x7b, 0x6b, 0x59, 0xc4, 0x76, 0xb0, 0x9d, 0x8a, 0xf2, 0x0a, 0xf0, 0x06, 0xbc, 0x03,
	0xcf, 0x88, 0x76, 0xed, 0xa4, 0x6e, 0xb9, 0x00, 0x12, 0x17, 0x6e, 0x9e, 0x99, 0xdd, 0xf9, 0x66,
	0x47, 0xfe, 0x40, 0x4d, 0xb3, 0x93, 0x75, 0x59, 0xd4, 0x05, 0x96, 0x2f, 0xe9, 0x32, 0x37, 0xbf,
	0x8a, 0xa0, 0x05, 0x69, 0x9e, 0xac, 0xa8, 0x5b, 0x25, 0xf8, 0x09, 0xc0, 0x55, 0x59, 0x64, 0x61,
	0x45, 0x4b, 0x27, 0x36, 0x84, 0xa1, 0x30, 0x92, 0x48, 0x87, 0xc1, 0x47, 0xa0, 0xd6, 0x45, 0xab,
	0x8a, 0x5c, 0xdd, 0x61, 0x6c, 0x40, 0x3f, 0x2a, 0xf2, 0x9a, 0xe6, 0xb5, 0x21, 0x0d, 0x85, 0x91,
	0x46, 0xb6, 0x90, 0xb9, 0x46, 0xab, 0x94, 0xe6, 0xf5, 0x3c, 0xcd, 0xa8, 0x21, 0x73, 0xb1, 0xc3,
	0x30, 0xbd, 0xa2, 0xe5, 0x35, 0x2d, 0xb9, 0xae, 0x34, 0xfa, 0x2d, 0xc3, 0x9c, 0xb3, 0x2a, 0x99,
	0xdf, 0xac, 0xa9, 0xd1, 0x6b, 0x9c, 0x5b, 0xc8, 0x94, 0xea, 0x26, 0x8f, 0x2e, 0xe8, 0x8d, 0xd1,
	0xe7, 0x71, 0xb6, 0x10, 0x1f, 0x82, 0x92, 0x55, 0x89, 0x13, 0x1b, 0x2a, 0xbf, 0xd1, 0x00, 0x36,
	0x29, 0xa6, 0xd7, 0x69, 0x44, 0xb9, 0x99, 0x36, 0x14, 0x46, 0x0a, 0xe9, 0x30, 0xe6, 0x37, 0x11,
	0x54, 0xbb, 0x2c, 0x36, 0xeb, 0xdf, 0x29, 0xe3, 0x31, 0x68, 0x75, 0xc1, 0x4f, 0xef, 0xda, 0xb8,
	0x25, 0xfe, 0x8b, 0x3a, 0x5e, 0x00, 0xb8, 0x55, 0x12, 0xd0, 0x3c, 0x26, 0xb4, 0xba, 0xf5, 0x10,
	0xba, 0x1e, 0x18, 0xe4, 0xab, 0xd5, 0x32, 0xe1, 0x05, 0xa8, 0x84, 0x7f, 0x9b, 0x9f, 0xa1, 0xe7,
	0x56, 0x09, 0xa1, 0x9f, 0xf0, 0x23, 0xe8, 0x6d, 0xba, 0xfd, 0xb5, 0xa8, 0x9b, 0x54, 0xbc, 0x9b,
	0xf4, 0x08, 0xd4, 0xf5, 0x32, 0xa1, 0x41, 0xfa, 0x85, 0xf2, 0xe2, 0x14, 0xb2, 0xc3, 0x78, 0x08,
	0x7a, 0xb4, 0x29, 0x4b, 0x9a, 0xd7, 0xb3, 0x65, 0xd2, 0x54, 0xa7, 0x90, 0x2e, 0x65, 0x9e, 0x83,
	0xd6, 0x4c, 0x66, 0x81, 0x3b, 0x43, 0x84, 0xbb, 0x43, 0x9e, 0x82, 0x9c, 0x55, 0x49, 0x65, 0x88,
	0x43, 0x69, 0xa4, 0x3f, 0x1b, 0x9c, 0xb0, 0x55, 0x38, 0xd9, 0xad, 0x01, 0xe1, 0xa2, 0xf9, 0x0a,
	0xd4, 0x69, 0x91, 0xa4, 0x39, 0x7b, 0xc7, 0x21, 0x28, 0x9b, 0xce, 0x33, 0x1a, 0x70, 0xaf, 0x3f,
	0xf1, 0x97, 0xfe, 0x5e, 0x6e, 0xd3, 0x9c, 0x46, 0x1f, 0xff, 0xbc, 0x8a, 0xf6, 0xba, 0x93, 0x5f,
	0x15, 0x65, 0xf6, 0x17, 0xd7, 0x3f, 0x80, 0x3e, 0x8f, 0xd6, 0x33, 0xb6, 0xec, 0x51, 0xb1, 0xc2,
	0x26, 0xec, 0xaf, 0xdb, 0x6f, 0x1e, 0x57, 0xe0, 0x71, 0xef, 0x70, 0x78, 0x04, 0x83, 0x2d, 0x1e,
	0xb7, 0x3f, 0x2f, 0x33, 0xdd, 0x27, 0xf7, 0x69, 0xf3, 0xbb, 0x00, 0x7a, 0x18, 0xff, 0x23, 0xf7,
	0x66, 0xb5, 0xc2, 0xf6, 0xbd, 0xd2, 0x76, 0xb5, 0x5a, 0x82, 0xfd, 0x06, 0x6c, 0x0d, 0x97, 0x71,
	0x5c, 0xd2, 0xaa, 0x6a, 0x37, 0xa8, 0x4b, 0x1d, 0xff, 0x10, 0x00, 0xcd, 0x3a, 0xa3, 0xad, 0x7c,
	0x93, 0x61, 0x1d, 0xfa, 0xa1, 0x77, 0xe1, 0xf9, 0xef, 0x3c, 0xb4, 0x87, 0x35, 0x50, 0xa6, 0xbe,
	0xed, 0x78, 0x48, 0xc0, 0x2a, 0xc8, 0x33, 0xdf, 0xb3, 0x91, 0xc8, 0x4e, 0xb8, 0x81, 0xbd, 0x20,
	0xd6, 0x1b, 0x24, 0xe1, 0x03, 0x00, 0x06, 0x1c, 0xef, 0xcc, 0x27, 0x2e, 0x92, 0xf1, 0x00, 0xf4,
	0x56, 0x5c, 0x10, 0x2b, 0x40, 0x4a, 0x97, 0x38, 0x1d, 0x5f, 0xa0, 0x1e, 0x7e, 0x08, 0x03, 0x46,
	0x04, 0x96, 0x37, 0x59, 0x04, 0x8e, 0x67, 0x4f, 0x2d, 0xd4, 0xc7, 0x18, 0x0e, 0x76, 0xa4, 0x4d,
	0xfc, 0x70, 0x86, 0x54, 0x8c, 0x60, 0x7f, 0xc7, 0x31, 0x2f, 0xed, 0x78, 0x01, 0xba, 0xdb, 0x2c,
	0xf1, 0x36, 0xea, 0xc4, 0x3a, 0x3b, 0x0d, 0xa7, 0x73, 0xb4, 0xc7, 0xf2, 0xcd, 0xad, 0xf7, 0x73,
	0x24, 0xb0, 0xd0, 0x96, 0xeb, 0x9f, 0x3b, 0x4d, 0xd4, 0x59, 0x18, 0xbc, 0x1e, 0xbb, 0x13, 0x24,
	0xe1, 0x3e, 0x48, 0x8e, 0x6b, 0x23, 0x99, 0x1d, 0x78, 0xeb, 0x3b, 0x63, 0x0b, 0x29, 0xf8, 0x01,
	0x68, 0xfc, 0x73, 0x31, 0xb1, 0x02, 0xd4, 0xbb, 0xec, 0xf1, 0x8a, 0x9f, 0xff, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0x54, 0xe1, 0x1c, 0xdd, 0x00, 0x06, 0x00, 0x00,
}
